### PR TITLE
;

### PR DESCRIPTION
**Pull request by cclauss**
Sorry about that...

### CODE REVIEW

**Comment by kangwonlee** [comment]
* Thanks for the `;`
* Additionally, I forgot about `if` block and comments
* I am working on an [additional branch](https://github.com/kangwonlee/travis-yml-conda-posix-nt/tree/feature/travis/enable).

**Comment by kangwonlee** [comment]
* 39dfee09272bd1e22a3f4e58b079b0e004881853 seems resolves this particular edit, IMHO.

**Comment by kangwonlee** [comment]
* Please see [test result](https://travis-ci.org/kangwonlee/travis-yml-conda-posix-nt/builds/516494378)

**Comment by cclauss** [comment]
https://travis-ci.org/kangwonlee/travis-yml-conda-posix-nt/jobs/516494384#L82 Seems to work OK.

**Pull request closed without merging**
